# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-18 03:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, help_text='Short description of event')),
                ('attachments', models.FileField(blank=True, upload_to='uploads/')),
                ('banner', models.ImageField(blank=True, default='/static/img/bg.jpg', help_text='Image thumbnail for event.', upload_to='event')),
                ('duration', models.PositiveIntegerField(blank=True, default=0, help_text='Please use hours format for event duration.')),
                ('registration_limit', models.IntegerField(verbose_name='Guest limit')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('nuid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=15)),
                ('registration_type', models.CharField(blank=True, choices=[('person', 'Attend in Person'), ('remote', 'Attend via Remote')], default='person', max_length=20)),
                ('department', models.CharField(blank=True, default='', max_length=15)),
                ('region', models.CharField(blank=True, default='', max_length=15)),
                ('email_address', models.EmailField(help_text='email address of attendee', max_length=254, verbose_name='attendee email')),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=15)),
                ('dietery_requirements', models.TextField(blank=True, default='', null=True)),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('confirm', 'Approved'), ('decline', 'Declined')], default='waiting', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Attendee')),
            ],
            options={
                'verbose_name': 'Attendee for event',
                'verbose_name_plural': 'Attendees for events',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Venue'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set([('event', 'email_address'), ('event', 'user')]),
        ),
    ]
