# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-02 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_add_thumbnail_on_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('confirm', 'Attending'), ('decline', 'Not Attending')], default='waiting', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Attendee'),
        ),
    ]
