# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-03 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_update_user_on_eventregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='email_address',
            field=models.EmailField(help_text='email address of attendee', max_length=254, verbose_name='attendee email'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='is_hotel',
            field=models.BooleanField(default=False, help_text='will be registering for hotel', verbose_name='hotel'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
