# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-03 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_update_email_on_eventregistration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set([('event', 'email_address'), ('event', 'user')]),
        ),
    ]
