# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-04 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_unique_email_on_eventregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='nuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
