# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-05 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_extra_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_limit',
            field=models.IntegerField(blank=True, default=0, verbose_name='Guest limit'),
        ),
    ]
