# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-05 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_add_end_date_on_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='nuid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
