# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-06 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_add_comments_on_event_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
