# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_remove_time_field_on_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_limit',
            field=models.IntegerField(verbose_name='Guest limit'),
        ),
    ]
