# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-12 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_remove_default_on_registration_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='nuid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='venue',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
