# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-11-29 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('person', 'Attend in Person'), ('remote', 'Attend via Remote')], default='person', max_length=20),
        ),
    ]
