# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-05 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_update_dietary_requirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='thumbnail',
            new_name='banner',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='event',
            name='num_of_attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_starts',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='is_hotel',
        ),
    ]
