# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-12-06 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 11, 43, 19, 699864, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('confirm', 'Approved'), ('decline', 'Declined')], default='waiting', max_length=10),
        ),
    ]
