# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_dt', models.DateField(blank=True, null=True)),
                ('event_title', models.CharField(blank=True, max_length=100, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event/', verbose_name='Event Banner')),
            ],
        ),
        migrations.CreateModel(
            name='Junkiri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(blank=True, null=True, upload_to='junkiri/', verbose_name='Junkiri post')),
                ('post_title', models.CharField(blank=True, max_length=100, null=True)),
                ('author_name', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('quote', models.TextField(blank=True, null=True)),
                ('post_dt', models.DateField(blank=True, null=True)),
                ('is_starring', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Display Picture'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('vice president', 'Vice sPresident'), ('outreach', 'Outreach'), ('treasurer', 'treasurer'), ('secretary', 'Secretary'), ('joint secretary', 'Joint Secretary')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='co_ordinated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Team'),
        ),
    ]
