# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190504_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, max_length=255, upload_to='image/', verbose_name='Image Post')),
            ],
        ),
    ]
