# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_show_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show_image',
        ),
    ]
