# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20190505_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junkiri',
            name='post_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Post Date'),
        ),
    ]
