# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190505_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junkiri',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Junkiri/%Y/%m', verbose_name='Junkiri Image'),
        ),
    ]
