# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190506_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junkiri',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, upload_to='Junkiri/%Y/%m', verbose_name='Junkiri Post'),
        ),
    ]
