# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-11 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190506_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/img/user.png', null=True, upload_to='profile/', verbose_name='Display Picture'),
        ),
    ]
