# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20190511_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default='/profile/user.png', null=True, upload_to='profile/', verbose_name='Display Picture'),
        ),
    ]
