# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20190512_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ended',
            field=models.BooleanField(default=False, verbose_name='End Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_upcoming',
            field=models.BooleanField(default=True, verbose_name='Upcoming Event'),
        ),
    ]
