# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190512_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_ongoing',
            field=models.BooleanField(default=False, verbose_name='Ongoing Event'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(blank=True, choices=[('President', 'President'), ('Vice president', 'Vice President'), ('Outreach', 'Outreach'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Joint secretary', 'Joint Secretary')], max_length=50, null=True),
        ),
    ]
