# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20190519_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_dt',
            field=models.DateTimeField(blank=True, help_text='Date should be in YYYY-MM-DD format i.e: 2011-11-11.', null=True, verbose_name='Event start date.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_dt',
            field=models.DateTimeField(blank=True, help_text='Date should be in YYYY-MM-DD format i.e: 2011-11-11.', null=True, verbose_name='Event end date.'),
        ),
    ]
