# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-16 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20190527_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='co_ordinated_by',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
